version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: typescript-npm-cli-template
    volumes:
      - .:/app:z
      - /app/node_modules
    working_dir: /app
    command: /app/bin/index.js
    env_file:
      - ./.env
